theme: jekyll-theme-dinky
title: Primer Reporte de Avances
description: 
<ul>
  <li>Celinna Arellano A01730562 </li>
  <li>Cristina Espinosa A01570388</li>
  <li>Daniela Cadena A01570603</li>
  <li>Diana Romero A01177903</li>
  <li>Edgardo Cantú A01283899</li>
</ul>
