theme: jekyll-theme-dinky
title: Primer Reporte de Avances
description: Celinna Arellano A01730562    Cristina Espinosa A01570388     Daniela Cadena A01570603    Diana Romero A01177903    Edgardo Cantú A01283899
