theme: jekyll-theme-dinky
title: Primer Reporte de Avances
description: Celinna Arellano A01730562 \nCristina Espinosa A01570388 \nDaniela Cadena A01570603 \nDiana Romero A01177903 \nEdgardo Cantú A01283899
